### ISSUE TITLE
OptAuto

### ISSUE THREAD

**Issue by fschloesser** [GregorCH/ipet#25]
Will optauto be fixed or discharded?

**Comment by GregorCH** [comment]
By the new reduction index feature, see issue #21 , it will be possible to compute optimal auto settings much more flexibly than before, and use this information to compute relative time to best, etc.

However, it is not possible to use such a column also in the aggregated table. The reason is that through the custom reduction index of a column, the reduced value may occur multiple times in the long table, and will be aggregated as such.

A way to enable this again would be to compute aggregations that respect the column reduction index, and fall back to the evaluation index if the column has no special index.

**Comment by GregorCH** [comment]
This has been addressed in the meantime. Evaluateoptauto has been marked as deprecated, the user is informed about the alternative of a custom reduction index.
