### ISSUE TITLE
issues I had during installation

### ISSUE THREAD

**Issue by fserra** [GregorCH/ipet#4]
Hey Gregor

good to see you here.

I just want to comment on some things I had to do to get ipet working again:  
In scripts/ipet-gui.py changed `qipetapplication = QIPETApplication()` for `qipetapplication = QIPETApplication.QIPETApplication()`  
In install-pyqt4-in-virtual-environment.sh I had to use #!/bin/bash as the first line  
In ipet/Experiment.py
```
     if arguments.saveexperiment is not False:
-        experiment.saveToFile(arguments.experimentfile)
+        experiment.saveToFile(arguments.saveexperiment)
```

**Comment by GregorCH** [comment]
Hi @fserra , thanks for the feedback. can you tell me which system you are using?

The first issue is rather fixed by adding
```
   from .QIPETApplication import QIPETApplication
```

to ipetgui/__init__.py. However, it is working in my installation without problems.

Concerning the install-pyqt4-script: I don't see the difference to the current use of #!/bin/bash at the top of the script.

Your third fix is not correct: If it is meant as it is currently. In case you provide an existing experimentfile, you may choose to override this experiment by calling 
```
   ipet-evaluate.py --experimentfile=myexperiment.ipx --recollect --saveexperiment.
```
You are, however, right, in that both these parameters were wrongly defined as String Parameters with default None. I changed this. I have to admit, I never use experiment files, because they are usually not flexible enough. Do you?

**Comment by fserra** [comment]
I am on Ubuntu 16.04

The script didn't run for me, saying that `usr/bin/bash` didn't exist

Me neither, I was just trying open the trn file with ipet-gui, but then I realized how to

thanks!

**Comment by GregorCH** [comment]
I am afraid that you must reparse the trn-files, if they were created with an older version if ipet-parse.py

**Comment by GregorCH** [comment]
Now I get it with the install script, I had the correct statement #!/bin/bash further down.

**Comment by svigerske** [comment]
Wouldn't it better be `#! /usr/bin/env bash` ?

**Comment by GregorCH** [comment]
Thanks, @svigerske, I changed that

**Comment by fserra** [comment]
this is still happening, but it seems you can't reopen an issue??
