### ISSUE TITLE
SCIPs time limit is not read / used

### ISSUE THREAD

**Issue by jakobwitzig** [GregorCH/ipet#55]
Somehow the time limit is not read or not correctly used by ipet. I would expect that the solving time will be capped by ipet if SCIP exceeds its time limit slightly, e.g., 7201.3 instead of 7200 seconds. Currently, ipet prints a time quotient != 1.0 if SCIP exceeds the time limit in two different runs slightly (e.g., 7200.3 and 7202.0) on the same instance.

Problematic would be if ipet uses the uncapped solving time for its internal calculations, which is in particular bad if a small time limit is used.

Thanks for fixing.
Jakob

**Comment by GregorCH** [comment]
This is intended. As a user, you have the freedom to cap the solving time, but IPET won't do it by itself. Just outputting 'SolvingTime' means "tell me whatever the solver reported". How else could you ever identify and repair cases where a solver needs significantly longer than the time limit.

In order to cap the solving time, use the 'maxval' attribute of the corresponding column. You can either use an explicit number, e.g., 7200, or use the value of another, exisiting column.
