### ISSUE TITLE
-n option ignored when loading evaluation file

### ISSUE THREAD

**Issue by fserra** [GregorCH/ipet#6]
when running ipet-evaluate.py -n etc, the -n is ignored once an evaluation file is loaded

**Comment by GregorCH** [comment]
I played around with it in the tests/examples/scip-miplip directory.

- Evaluation via `ipeval -t benchmark.scip*.trn -n` works fine
- Opening the evaluation editor app with -A works fine and has "evaluateoptauto" set correctly to False.
- Loading the evaluation into the app again has evaluateoptauto set to True, and I guess that is what you mean.

The reason is that the methods responsible for processing the XML representation of an evaluation are currently out of sync.

**Comment by GregorCH** [comment]
This issue was fixed on the current master.
