### ISSUE TITLE
ipet cannot handle empty lines in a solution file

### ISSUE THREAD

**Issue by jakobwitzig** [GregorCH/ipet#72]
When a solution file has empty lines I get
```
Traceback (most recent call last):
  File "<my-path>/ipet/scripts/ipet-parse", line 140, in <module>
    experiment.addSoluFile(solufile)
  File "<my-path>/ipet/ipet/Experiment.py", line 109, in addSoluFile
    self.validation = Validation(solufilename, self.gaptol)
  File "<my-path>/ipet/ipet/validation/Validation.py", line 51, in __init__
    self.referencedict = self.readSoluFile(solufilename)
  File "<my-path>/ipet/ipet/validation/Validation.py", line 80, in readSoluFile
    marker = spline[0]
IndexError: list index out of range
```
It would be nice if this easy case can handled by ipet without a crash.

**Comment by GregorCH** [comment]
Then your solu file does not meet the format requirements for a solu file.

Lately, I have decided to call solu file information "reference information". I am currently reworking the reference information format (at least three fields for an instance primal and dual bound and the objective sense), which is why I would prefer not to struggle against formatting issues that can be simply fixed on the user side for the old format.

**Comment by jakobwitzig** [comment]
> Then your solu file does not meet the format requirements for a solu file.

This might be, but such an easy case can / should be handled without a crash. Sure, the empty lines can be easily removed with an sed command but it would be user-friendly to skip these lines.
